---

- stat: path=/vagrant
  register: v

# skip if we're using vagrant
- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ sshd_port }}"
  #notify: "Restart sshd"
  when: v.stat.exists == false